User.create(name: "Steve", email: "stevem@gmail.com", password: "medabest")
User.create(name: "David", email: "david@hotmail.com", password: "codingsawesome")
Task.create(content: "I must move the car", user_id: 1 )
Task.create(content: "need to take notes", user_id: 1 )
Task.create(content: "go to work", user_id: 2 )
